services:
    jupyter:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          VARIANT: lab-4.2.3
      ports:
        - 8889:8888
      volumes:
        - jupyter-home:/home
        - ./examples:/home/jovyan/examples
      command: start-notebook.py --NotebookApp.token='my-token'
  
volumes:
  jupyter-home: